create table if not exists public.email_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text,
  created_at timestamptz not null default now()
);

alter table public.email_signups enable row level security;

create policy "Allow anonymous email signups"
on public.email_signups
for insert
to anon
with check (true);
