create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  page text not null,
  label text,
  section text,
  href text,
  site_host text,
  visitor_id text not null,
  session_id text not null,
  created_at timestamptz not null default now()
);

alter table public.site_events enable row level security;

drop policy if exists "Allow anonymous site events" on public.site_events;
create policy "Allow anonymous site events"
on public.site_events
for insert
to anon
with check (true);

drop policy if exists "Allow anonymous site event reads" on public.site_events;
create policy "Allow anonymous site event reads"
on public.site_events
for select
to anon
using (true);
